"""add table Payment

Revision ID: 4b8257b3ec8e
Revises: db0000baa551
Create Date: 2026-05-06 22:02:31.346831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b8257b3ec8e'
down_revision: Union[str, Sequence[str], None] = 'db0000baa551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pay_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('deeplink', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('qr_code_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_code', sa.Integer(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_request_id'), 'payment_transactions', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transactions_request_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
