"""add clumn module_id

Revision ID: aa1114ca1df0
Revises: 89c70215afa9
Create Date: 2026-05-27 22:59:59.395727

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1114ca1df0'
down_revision: Union[str, Sequence[str], None] = '89c70215afa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('curriculum_module_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'curriculum_modules', ['curriculum_module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'curriculum_module_id')
    # ### end Alembic commands ###
