"""add curriculum_module_id to material_chunks

Revision ID: c6ad943844ce
Revises: f9a1fc26d09c
Create Date: 2026-04-25 21:25:59.453508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6ad943844ce'
down_revision: Union[str, Sequence[str], None] = 'f9a1fc26d09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('is_time_up', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_assessment_attempts_project_id_projects'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_assessment_attempts_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_module_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_module_id'], ['curriculum_modules.id'], name='fk_material_chunks_curriculum_module_id_curriculum_modules'),
    sa.ForeignKeyConstraint(['material_id'], ['learning_materials.id'], name='fk_material_chunks_material_id_learning_materials'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answers', sa.Column('attempt_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_answers_attempt_id_assessment_attempts',
        'answers',
        'assessment_attempts',
        ['attempt_id'],
        ['id'],
    )
    op.add_column('questions', sa.Column('assignments_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_questions_assignments_id_assignments',
        'questions',
        'assignments',
        ['assignments_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_questions_assignments_id_assignments', 'questions', type_='foreignkey')
    op.drop_column('questions', 'assignments_id')
    op.drop_constraint('fk_answers_attempt_id_assessment_attempts', 'answers', type_='foreignkey')
    op.drop_column('answers', 'attempt_id')
    op.drop_table('material_chunks')
    op.drop_table('assessment_attempts')
    # ### end Alembic commands ###
