"""add pricing plan subscription fields

Revision ID: db0000baa551
Revises: 20260505adminstats
Create Date: 2026-05-06 06:58:28.457799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db0000baa551'
down_revision: Union[str, Sequence[str], None] = '20260505adminstats'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'attempt_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('answers', 'text_answer',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('pricing_plans', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pricing_plans', sa.Column('billing_cycle', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='monthly'))
    op.add_column('pricing_plans', sa.Column('max_project', sa.Integer(), nullable=True))
    op.add_column('pricing_plans', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('pricing_plans', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('pricing_plans', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pricing_plans', sa.Column('bagde_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pricing_plans', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('pricing_plans', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_pricing_plans_name'), 'pricing_plans', ['name'], unique=True)
    op.alter_column('question_options', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_question_options_question_id_questions'), 'question_options', type_='foreignkey')
    op.create_foreign_key(None, 'question_options', 'questions', ['question_id'], ['id'])
    op.alter_column('questions', 'assignments_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('questions', 'explanation',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_questions_curriculum_module_id_curriculum_modules'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'curriculum_modules', ['curriculum_module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_questions_curriculum_module_id_curriculum_modules'), 'questions', 'curriculum_modules', ['curriculum_module_id'], ['id'], ondelete='SET NULL')
    op.alter_column('questions', 'explanation',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('questions', 'assignments_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'question_options', type_='foreignkey')
    op.create_foreign_key(op.f('fk_question_options_question_id_questions'), 'question_options', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('question_options', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_pricing_plans_name'), table_name='pricing_plans')
    op.drop_column('pricing_plans', 'update_at')
    op.drop_column('pricing_plans', 'created_at')
    op.drop_column('pricing_plans', 'bagde_text')
    op.drop_column('pricing_plans', 'display_order')
    op.drop_column('pricing_plans', 'is_featured')
    op.drop_column('pricing_plans', 'is_active')
    op.drop_column('pricing_plans', 'max_project')
    op.drop_column('pricing_plans', 'billing_cycle')
    op.drop_column('pricing_plans', 'description')
    op.alter_column('answers', 'text_answer',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('answers', 'attempt_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
